1248-drowpdown-list-overflow-bottom-of-page
openforis/arena pull request #1261
Opened 2020-11-15 20:23 UTC by ramirobg94

fixes #1248

2020-11-16 08:32 UTC, SteRiccio approved these changes

2020-11-16 09:02 UTC, minotogna requested changes

2020-11-16 09:02 UTC, minotogna commented on webapp/components/form/AutocompleteDialog/store/state/state.js
> +}
does this open the dropdown on top?
if yes, then it shouldn't. update body height

2020-11-17 18:53 UTC, minotogna commented on webapp/components/form/AutocompleteDialog/store/state/state.js
> +}
because users aren't used to that

2020-11-18 09:07 UTC, minotogna approved these changes

2020-11-18 10:47 UTC, merged