replace date input component
openforis/arena pull request #1313
Opened 2020-12-01 17:21 UTC by ramirobg94

2020-12-01 18:42 UTC, minotogna requested changes

2020-12-01 18:42 UTC, minotogna commented on webapp/components/survey/SurveyForm/nodeDefs/components/types/nodeDefDate.js
> +      <DateInput
this component must be wrapped into a common component to be used also in other places

2020-12-02 08:26 UTC, SteRiccio commented on package.json
> +    "react-input-date": "^1.0.2",
who is managing the source code of this library? why don't we put it in github.com/openforis/...?

2020-12-04 08:48 UTC, SteRiccio requested changes

2020-12-08 10:19 UTC, minotogna requested changes

2020-12-08 10:19 UTC, minotogna commented on webapp/components/form/DateInput/ReactDateInput/component.js
> +            <small>Invalid date</small>
texts must be added to i18n

2020-12-08 10:19 UTC, minotogna commented on webapp/components/form/DateInput/ReactDateInput/component.js
> +            <small>Incomplete date</small>
same as above

2020-12-16 13:22 UTC, minotogna submitted a review, later dismissed

2020-12-17 08:58 UTC, SteRiccio approved these changes

2020-12-17 08:58 UTC, SteRiccio commented on webapp/components/form/DateInput/ReactDateInput/component.js
> +    const [elRefs, setElRefs] = React.useState([])
use just `useState`

2020-12-17 22:56 UTC, SteRiccio approved these changes

2020-12-18 00:53 UTC, merged