Enhancement/survey export UI test e2e
openforis/arena pull request #1349
Opened 2021-01-14 23:32 UTC by ramirobg94

2021-01-18 09:49 UTC, SteRiccio approved these changes

2021-01-19 07:32 UTC, minotogna requested changes
please see my comments

2021-01-19 07:32 UTC, minotogna commented on test/e2e/tests/017-surveyExport.js
> +import extract from 'extract-zip'
better to create a common file that wraps the zip extraction

2021-01-19 07:32 UTC, minotogna commented on test/e2e/tests/017-surveyExport.js
> +import csvParseSync from 'csv-parse/lib/sync'
don't we have a CSV reader already ?

2021-01-20 08:43 UTC, minotogna approved these changes

2021-01-20 08:44 UTC, merged