Enhancement/import survey users
openforis/arena pull request #1359
Opened 2021-01-25 17:12 UTC by ramirobg94

2021-01-27 08:43 UTC, minotogna requested changes

2021-01-27 08:43 UTC, minotogna commented on test/e2e/tests/018-surveyImport.js
> +import fs from 'fs'
please, split this into sub files

2021-01-27 08:59 UTC, SteRiccio requested changes

2021-01-27 08:59 UTC, SteRiccio commented on test/e2e/tests/018-surveyImport.js
> +    await taxonomy.reduce(async (promise, taxon) => {
would `await PromiseUtils.each(taxonomy, async taxon => {...})` be more readable?

2021-01-28 08:54 UTC, SteRiccio commented on test/e2e/utils/surveyExport/categories.js
> +const checkItemDiscrictLevel = async ({ item, index, itemsRegionLevel, districtLevel }) => {
just a typo... discrict...

2021-01-28 08:54 UTC, SteRiccio commented on test/e2e/utils/surveyExport/categories.js
> +const checkLevelAndReturnLevel = async ({ levels, categoryName, index }) => {
categoryName must be renamed into levelName

2021-01-28 11:08 UTC, minotogna approved these changes

2021-01-28 11:24 UTC, SteRiccio approved these changes

2021-01-28 11:27 UTC, merged