change style
openforis/arena pull request #1386
Opened 2021-02-15 15:26 UTC by ramirobg94

resolves #1355
And fixes the style of the r-studio button too

![Captura de pantalla 2021-02-15 a las 16 21 19](https://user-images.githubusercontent.com/11272068/107964786-f1b10b00-6fa9-11eb-83d2-e06f50c2d3c8.png)

![Captura de pantalla 2021-02-15 a las 16 21 27](https://user-images.githubusercontent.com/11272068/107964779-efe74780-6fa9-11eb-8566-0473ffedce3e.png)

=============

![Captura de pantalla 2021-02-15 a las 16 22 33](https://user-images.githubusercontent.com/11272068/107964829-042b4480-6faa-11eb-80ff-091a4219dc02.png)

![Captura de pantalla 2021-02-15 a las 16 23 03](https://user-images.githubusercontent.com/11272068/107964880-15745100-6faa-11eb-87dc-92e9768c16af.png)

2021-02-16 10:12 UTC, SteRiccio submitted a review, later dismissed

2021-02-16 11:08 UTC, minotogna requested changes

2021-02-16 11:08 UTC, minotogna commented on webapp/style/table.scss
> +  display: unset;
this doesn't look right. check if there's another solution

2021-02-17 06:49 UTC, minotogna approved these changes

2021-02-17 07:15 UTC, merged