Disable innactive areabased
openforis/arena pull request #2028
Opened 2021-12-21 14:34 UTC by ramirobg94

2021-12-21 23:01 UTC, SteRiccio requested changes

2021-12-21 23:01 UTC, SteRiccio commented on core/survey/_survey/surveyAnalysis.js
> +        Boolean(NodeDef.getAreaBasedEstimatedOf(nodeDef)) &&
Boolean(NodeDef.getAreaBasedEstimatedOf(nodeDef)) can be replaced with isAreaBasedEstimatedOf.. isn't it?

2021-12-22 01:08 UTC, ramirobg94 commented on core/survey/_survey/surveyAnalysis.js
> +        Boolean(NodeDef.getAreaBasedEstimatedOf(nodeDef)) &&
```suggestion
       NodeDef. isAreaBasedEstimatedOf(nodeDef) &&
```

2021-12-22 01:08 UTC, ramirobg94 commented on core/survey/_survey/surveyAnalysis.js
> +       NodeDef. isAreaBasedEstimatedOf(nodeDef) &&
```suggestion
       NodeDef.isAreaBasedEstimatedOf(nodeDef) &&
```

2021-12-22 08:18 UTC, SteRiccio approved these changes

2021-12-22 08:18 UTC, merged