Hide result variables based on role
openforis/arena pull request #2052
Opened 2022-01-17 08:30 UTC by ramirobg94

resolves #1998

2022-01-18 08:20 UTC, SteRiccio requested changes

2022-01-18 08:20 UTC, SteRiccio commented on webapp/store/user/hooks.js
> +export const useAuthcanUseAnalysis = () => Authorizer.canAnalyzeRecords(useUser(), useSurveyInfo())
very stupid thing, useAuthcanUseAnalysis should be useAuthCanUseAnalysis, just to be consistent with the other hooks

2022-01-18 11:55 UTC, ramirobg94 commented on webapp/store/user/index.js
> +  useAuthcanUseAnalysis,
```suggestion
  useAuthCanUseAnalysis,
```

2022-01-18 11:55 UTC, ramirobg94 commented on webapp/store/user/index.js
> +  useAuthcanUseAnalysis,
```suggestion
  useAuthCanUseAnalysis,
```

2022-01-18 11:55 UTC, ramirobg94 commented on webapp/store/user/hooks.js
> +export const useAuthcanUseAnalysis = () => Authorizer.canAnalyzeRecords(useUser(), useSurveyInfo())
```suggestion
export const useAuthCanUseAnalysis = () => Authorizer.canAnalyzeRecords(useUser(), useSurveyInfo())
```

2022-01-18 11:55 UTC, ramirobg94 commented on webapp/components/survey/SurveyDefsLoader/SurveyDefsLoader.js
> +import { useAuthcanUseAnalysis } from '@webapp/store/user'
```suggestion
import { useAuthCanUseAnalysis } from '@webapp/store/user'
```

2022-01-18 11:55 UTC, ramirobg94 commented on webapp/components/survey/SurveyDefsLoader/SurveyDefsLoader.js
> +  const includeAnalysis = useAuthcanUseAnalysis()
```suggestion
  const includeAnalysis = useAuthCanUseAnalysis()
```

2022-01-20 16:39 UTC, SteRiccio approved these changes

2022-01-20 16:40 UTC, merged